export const CAREER_HANDBOOK_META = Object.freeze({
  title: 'Road to Glory to Head Coach',
  subtitle: 'EA SPORTS College Football 27 Immersive Career Handbook',
  edition: 'Reference edition - August 2026',
  concept: 'A 6\'1", 205-pound left-handed dual-threat quarterback from Dearborn, Michigan earns his college opportunity, finishes his playing career, then begins Dynasty as the offensive coordinator at his final school before working toward a head-coaching job.',
  payoff: 'Realism with a playable payoff',
  northStar: 'An undersized Michigan quarterback earns his opportunity, develops into a college starter, learns the offense through adversity, and eventually returns to the sideline as an offensive coordinator before earning the right to lead a program of his own.',
  closing: 'Realism creates the stakes. Playing time creates the memories.',
});

export const CAREER_HANDBOOK_STAGE_GUIDE = Object.freeze([
  ['Player creation', 'Sections 1-3', 'Identity, ceilings and abilities'],
  ['High school', 'Sections 4-5', 'Star-rating branches and recruiting board'],
  ['Commitment decision', 'Section 6', 'School-selection scorecard'],
  ['College career', 'Sections 7-10', 'Seasonal arc, gameplay and transfers'],
  ['After RTG', 'Sections 11-13', 'Guardrails, coaching backstory and Dynasty rules'],
  ['Ongoing reference', 'Section 14', 'Checklists and tracking'],
]);

const table = (columns, rows) => ({ type: 'table', columns, rows });
const bullets = (items) => ({ type: 'bullets', items });
const numbered = (items) => ({ type: 'numbered', items });
const paragraph = (text) => ({ type: 'paragraph', text });
const subheading = (text) => ({ type: 'subheading', text });
const callout = (title, text) => ({ type: 'callout', title, text });

export const CAREER_HANDBOOK_SECTIONS = Object.freeze([
  {
    id: 'player-identity',
    number: 1,
    title: 'Player Identity',
    stage: 'Player creation',
    content: [
      table(['Item', 'Choice'], [
        ['Position', 'Quarterback'],
        ['Archetype', 'Dual Threat'],
        ['Height / weight', '6\'1" / 205 lb'],
        ['Hometown', 'Dearborn, Michigan'],
        ['High school', 'Edsel Ford Thunderbirds'],
        ['Throwing hand', 'Left'],
        ['Jersey number', 'No. 2'],
        ['Style', 'Pass-first creator with designed-run value'],
        ['Personality', 'Competitive, composed, team-oriented'],
      ]),
      subheading('Scouting profile'),
      bullets([
        'Quick accelerator who can punish man coverage and extend plays.',
        'Comfortable on RPOs, movement throws and quick-game concepts.',
        'Good arm talent, but not a generational cannon.',
        'Needs better deep-ball consistency, pocket patience and pressure recognition.',
        'Undersized by traditional standards, which supports the original three-star storyline.',
      ]),
      callout('Player identity rule', 'He is a quarterback who can run, not a running back who happens to throw. Scrambling should complement the offense rather than replace reading the defense.'),
    ],
  },
  {
    id: 'attribute-ceiling',
    number: 2,
    title: 'Star-Neutral Attribute Ceiling',
    stage: 'Player creation',
    intro: 'Use one balanced, high-upside ceiling before high school. The final star rating changes expectations, offers and career pressure - not the talent profile you already created.',
    content: [
      subheading('Passing attributes'),
      table(['Attribute', 'Target cap', 'Purpose'], [
        ['Throw Power', '93', 'Strong enough for every college throw'],
        ['Short Accuracy', '92', 'Primary accuracy strength'],
        ['Medium Accuracy', '90', 'Reliable upperclassman potential'],
        ['Deep Accuracy', '87', 'Clear relative weakness'],
        ['Throw on the Run', '93', 'Signature passing trait'],
        ['Throw Under Pressure', '88', 'Good ceiling, not automatic'],
        ['Play Action', '86', 'Useful secondary skill'],
        ['Break Sack', '79', 'Prevents unrealistic escape ability'],
      ]),
      subheading('Athletic attributes'),
      table(['Attribute', 'Target cap', 'Purpose'], [
        ['Speed', '91', 'Dangerous without track-star cheese'],
        ['Acceleration', '94', 'Best physical trait'],
        ['Agility', '89', 'Escape and reset ability'],
        ['Change of Direction', '90', 'Option and open-field value'],
        ['Carrying', '84', 'Requires ball-security decisions'],
        ['Stamina', '93', 'Supports a dual-threat workload'],
        ['Strength', '70', 'Realistic for the frame'],
        ['Toughness', '87', 'Resilient, not invulnerable'],
        ['Injury', '88', 'Durability still matters'],
      ]),
      subheading('Allocation order'),
      numbered([
        'Throw on the Run', 'Acceleration', 'Short Accuracy', 'Throw Power', 'Speed',
        'Medium Accuracy', 'Change of Direction', 'Carrying', 'Throw Under Pressure',
        'Stamina', 'Agility', 'Deep Accuracy', 'Toughness / Injury', 'Play Action', 'Break Sack',
      ]),
      callout('If points run short', 'Reduce Play Action, Break Sack, Deep Accuracy, Agility, Throw Under Pressure and Change of Direction - in that order. Preserve the core identity: acceleration, throwing on the run, short accuracy, throw power and reasonable speed.'),
    ],
  },
  {
    id: 'development',
    number: 3,
    title: 'Development and Cap-Breaker Rules',
    stage: 'Player creation',
    intro: 'Treat ceiling values as potential, not guaranteed outcomes. Skill points should develop the player gradually, and earned Cap Breakers should represent major career growth.',
    content: [
      table(['Career stage', 'Primary development'], [
        ['Freshman', 'Short Accuracy, Throw on the Run, Carrying, basic pressure recognition'],
        ['Sophomore', 'Medium Accuracy, Throw Under Pressure, Throw Power, Acceleration'],
        ['Junior', 'Full-field passing, Change of Direction, situational composure'],
        ['Senior / final year', 'Deep Accuracy, durability and weaknesses revealed by gameplay'],
      ]),
      subheading('Cap-Breaker philosophy by final rating'),
      table(['Rating', 'Meaning', 'Use breakers after...'], [
        ['3-star', 'Proving scouts wrong', 'Winning the job, all-conference honors, records or a title'],
        ['4-star', 'Turning recognized upside into elite play', 'A major breakout season or sustained success'],
        ['5-star', 'Separating a top recruit from a truly rare player', 'National awards, championships or historic production'],
      ]),
      bullets([
        'Prioritize Throw Under Pressure, Deep Accuracy, Medium Accuracy and Carrying.',
        'Use physical breakers sparingly. Do not automatically push Speed or Acceleration toward 99.',
        'A five-star who performs merely well should develop toward his existing ceiling, not exceed it everywhere.',
      ]),
    ],
  },
  {
    id: 'star-branches',
    number: 4,
    title: 'High-School Star-Rating Branches',
    stage: 'High school',
    content: [
      table(['Final rating', 'Story', 'College level', 'Starting expectation'], [
        ['3-star', 'Overlooked local prospect', 'MAC / comparable Group of Five', 'Compete by junior year'],
        ['4-star', 'Late-rising regional star', 'Strong G5 or middle Power Four', 'Sophomore or junior'],
        ['5-star', 'Unexpected national breakout', 'Power Four, including rebuilds and contenders', 'Freshman through junior, depending on room'],
      ]),
      subheading('3-star path'),
      bullets([
        'Begin around QB3 behind an older starter.',
        'Freshman year is developmental; sophomore year should produce a QB2 role.',
        'Junior year is the deadline for a genuine starting competition.',
        'Transfer only when a younger quarterback blocks the path or the scheme changes.',
      ]),
      subheading('4-star path'),
      bullets([
        'Begin as QB2 or a competitive QB3.',
        'A serious sophomore competition becomes realistic.',
        'A Power Four offer is believable, but loyalty to an early G5 recruiter remains compelling.',
        'By junior year, starting or transferring should be the expectation.',
      ]),
      subheading('5-star path'),
      bullets([
        'Do not automatically select the biggest brand or guaranteed Week 1 job.',
        'Choose among a regional power, a rebuilding Power Four program or a blue-blood competition.',
        'Sitting one year can be realistic; remaining QB3 deep into the career requires a transfer decision.',
        'Add pressure: poor performances, fan expectations and draft projections become part of the story.',
      ]),
    ],
  },
  {
    id: 'opening-board',
    number: 5,
    title: 'Opening Top 10 Interested Schools',
    stage: 'High school',
    intro: 'Start the board as a regional three-star prospect. Let high-school performance bring larger programs into the recruitment naturally.',
    content: [
      table(['Rank', 'School', 'Opening role on the board'], [
        ['1', 'Eastern Michigan', 'Hometown favorite and strongest full-career story'],
        ['2', 'Western Michigan', 'In-state development with championship potential'],
        ['3', 'Toledo', 'Regional contender and strong competitive fit'],
        ['4', 'Central Michigan', 'Michigan tradition and program-building opportunity'],
        ['5', 'Bowling Green', 'Nearby developmental option'],
        ['6', 'Ohio', 'Balanced scheme and mobile-QB development'],
        ['7', 'Miami (Ohio)', 'Winning, academics and stability'],
        ['8', 'Northern Illinois', 'Midwest Mountain West opportunity with national travel'],
        ['9', 'Ball State', 'Lower-pressure program-builder path'],
        ['10', 'Cincinnati', 'Regional Power Four stretch school'],
      ]),
      callout('Conference note', 'Northern Illinois is treated here as a Mountain West football member, not a MAC program. It remains realistic because of its Midwest location, but its travel and conference identity create a different storyline.'),
      subheading('How the board evolves'),
      table(['Current rating', 'Board rule'], [
        ['Still 3-star', 'Keep the original board mostly intact; finalists should usually be regional G5 programs.'],
        ['Rise to 4-star', 'Keep 5-6 original schools and add programs such as Purdue, Indiana, Michigan State or Northwestern when offered.'],
        ['Rise to 5-star', 'Keep about 3 early believers, add regional Power Four choices, national contenders and program-building options.'],
      ]),
      subheading('Example 4-star board'),
      paragraph('Eastern Michigan, Toledo, Western Michigan, Cincinnati, Purdue, Indiana, Central Michigan, Michigan State, Ohio and Northwestern.'),
      subheading('Example 5-star board'),
      paragraph('Michigan State, Cincinnati, Purdue, Indiana, Eastern Michigan, Toledo, Louisville, Penn State, Tennessee and Oregon. Only use schools that actually show interest or offer in your save.'),
    ],
  },
  {
    id: 'commitment-scorecard',
    number: 6,
    title: 'Commitment Scorecard',
    stage: 'Commitment decision',
    content: [
      table(['Category', 'Weight', 'Question'], [
        ['Path to starting by junior year', '30%', 'Does the current room create a real opening?'],
        ['Scheme fit', '25%', 'Does the offense use RPOs, movement throws and QB runs?'],
        ['Coaching stability', '15%', 'Is the staff likely to remain long enough to develop you?'],
        ['Regional / personal connection', '10%', 'Does the choice fit the backstory?'],
        ['Supporting roster', '10%', 'Will the line and skill talent help development?'],
        ['Program prestige', '5%', 'Is the level appropriate for the rating earned?'],
        ['Brand / exposure', '5%', 'Does it add value without overpowering football fit?'],
      ]),
      callout('Ideal final three', 'Create three different choices: Loyalty (an early believer), Development (the best football fit), and Opportunity (the highest level you earned). Do not simply choose the school with the most stars.'),
      subheading('Ideal quarterback room'),
      bullets([
        'QB1: established junior or senior.',
        'QB2: average upperclassman or beatable younger player.',
        'You: developmental freshman QB3, or QB2 if you finish as a higher-rated recruit.',
        'Avoid an elite freshman or sophomore already established as the long-term starter.',
        'Verify the actual in-game depth chart before committing; real-world rosters may not match the game.',
      ]),
    ],
  },
  {
    id: 'college-arc',
    number: 7,
    title: 'Recommended College Career Arc',
    stage: 'College career',
    content: [
      table(['Season', 'Expected role', 'Realistic goal'], [
        ['Freshman', 'QB3, possibly QB2', 'Learn the offense and earn trust'],
        ['Sophomore', 'QB2 or open competition', 'Receive packages, relief snaps or limited starts'],
        ['Junior', 'Starting competition', 'Win the job or earn a justified transfer'],
        ['Senior / final year', 'Starter', 'Finish as a two-year starter or capitalize on one final opportunity'],
      ]),
      subheading('Junior-year decision tree'),
      bullets([
        'Win the job: stay and play junior and senior seasons.',
        'Lose narrowly to a senior: stay if you remain QB2 and are clearly next.',
        'Lose to a younger quarterback: finish the season appropriately, then enter the portal.',
        'Remain QB3: transfer after the season; three developmental years are enough.',
      ]),
      callout('Realism boundary', 'Realism should create stakes, not eliminate participation. It is reasonable to earn the job. It is not necessary to accept a stagnant depth chart after the game has clearly shown there is no viable path.'),
    ],
  },
  {
    id: 'weekly-agenda',
    number: 8,
    title: 'Weekly Agenda and Off-Field Priorities',
    stage: 'College career',
    content: [
      table(['Season', 'Priority order'], [
        ['Freshman', 'Academics -> Training -> Health -> Leadership -> Brand'],
        ['Sophomore', 'Training -> Academics -> Leadership -> Health -> Brand'],
        ['Junior', 'Leadership -> Training -> Health -> Brand -> Academics'],
        ['Senior', 'Let draft goals, team leadership and health shape the order'],
      ]),
      bullets([
        'Never completely neglect academics to chase ratings.',
        'Use Brand only when it makes sense for the player\'s on-field success.',
        'Prioritize Health after heavy rushing games or visible wear and tear.',
      ]),
    ],
  },
  {
    id: 'gameplay-rules',
    number: 9,
    title: 'Gameplay House Rules',
    stage: 'College career',
    content: [
      subheading('Scrambling'),
      bullets([
        'Scramble when protection breaks down, man coverage opens a lane, the play is designed for it, or the progression is exhausted.',
        'Do not immediately sprint outside the pocket after every snap.',
        'Make at least one legitimate read before improvising, unless the defense brings immediate pressure.',
      ]),
      subheading('Quarterback carries'),
      table(['Game type', 'Target carries'], [
        ['Normal game', '6-10'],
        ['Option-heavy matchup', '10-14'],
        ['Rivalry / championship', 'Up to 16 when the game demands it'],
      ]),
      subheading('Passing and play-calling'),
      bullets([
        'Use checkdowns and throwaways.',
        'Limit major hot-route changes to two on a play.',
        'Do not spam a concept because the AI cannot stop it.',
        'Accept inaccurate throws, interceptions and road struggles.',
        'Never restart because of a bad result.',
      ]),
      subheading('Contact and durability'),
      bullets([
        'Slide in ordinary open-field situations.',
        'Run out of bounds when the extra yard is not essential.',
        'Fight through contact only near the sticks, goal line or in major late-game moments.',
        'Become more conservative after several hard hits.',
      ]),
    ],
  },
  {
    id: 'transfer-rules',
    number: 10,
    title: 'Transfer Portal Rules',
    stage: 'College career',
    content: [
      subheading('Transfer is justified when'),
      bullets([
        'You remain QB3 after three seasons.',
        'A younger quarterback is named the future starter.',
        'The coach who recruited you leaves or the scheme becomes incompatible.',
        'Your rating and resume clearly justify a starting opportunity elsewhere.',
        'You graduate and pursue one final season as a starter.',
      ]),
      subheading('Transfer is not justified when'),
      bullets([
        'You miss the playoff or lose one competition.',
        'A larger brand offers slightly more prestige.',
        'You throw several interceptions and want to reset the story.',
        'You are the established starter but simply want an easier championship path.',
      ]),
      callout('Default limit', 'Use one primary transfer. A second move should require an unusual coaching, academic or depth-chart event.'),
    ],
  },
  {
    id: 'statistical-guardrails',
    number: 11,
    title: 'Statistical Guardrails',
    stage: 'After RTG',
    content: [
      table(['Stage', 'Passing', 'Rushing'], [
        ['First full starting season', '2,400-3,100 yd; 18-26 TD; 8-14 INT; 58-65%', '400-750 yd; 5-10 TD'],
        ['Experienced starter', '2,900-3,700 yd; 24-34 TD; 6-12 INT; 62-68%', '500-900 yd; 6-12 TD'],
      ]),
      paragraph('These are guardrails, not quotas. Exceptional seasons can exceed them, but repeated extreme numbers may indicate that the difficulty, play calling or scrambling rules need adjustment.'),
    ],
  },
  {
    id: 'player-to-coach',
    number: 12,
    title: 'Transition From Player to Coach',
    stage: 'After RTG',
    intro: 'After RTG, recreate the player as a Dynasty coach. Use a compressed fictional apprenticeship so the first OC job feels plausible.',
    content: [
      table(['Step', 'Fictional role'], [
        ['1', 'Graduate assistant at his final college'],
        ['2', 'Offensive quality-control assistant'],
        ['3', 'Quarterbacks coach at a smaller program'],
        ['4', 'Passing-game coordinator'],
        ['5', 'Offensive coordinator at the final school he played for'],
      ]),
      callout('Connected narrative', 'The final school matters twice: it completes the playing career and becomes the emotional foundation of the coaching career.'),
      subheading('Coaching identity'),
      table(['Item', 'Choice'], [
        ['Archetype', 'Offensive strategist and player developer'],
        ['Base scheme', 'Multiple Spread'],
        ['Core concepts', 'Quick game, RPOs, zone read, moving pockets, play action and selective vertical shots'],
        ['Primary pipeline', 'Michigan'],
        ['Secondary pipeline', 'Ohio / Midwest'],
        ['Recruiting belief', 'Traits and fit over stars and prototype size'],
      ]),
    ],
  },
  {
    id: 'dynasty-movement',
    number: 13,
    title: 'Dynasty Career Movement Rules',
    stage: 'After RTG',
    content: [
      bullets([
        'Begin as OC at the final school from RTG.',
        'Remain at the first OC job for at least two seasons.',
        'Do not accept a head-coaching job after one good year.',
        'Consider another OC job only when it is a clear professional step.',
        'The first head-coaching job should normally be at a Group of Five school or a struggling lower-tier Power Four program.',
        'Do not jump directly from small-school OC to national-power head coach.',
        'Only pursue positions that fit the resume, scheme, pipelines and geographic story.',
      ]),
      table(['Career phase', 'Suggested window'], [
        ['OC at final RTG school', 'Years 1-2 or longer'],
        ['Higher-level OC opportunity', 'Years 3-5, only if earned'],
        ['First head-coaching job', 'Around Years 5-8'],
        ['Major program opportunity', 'After sustained head-coaching success'],
      ]),
      subheading('How the recruiting rating shapes the future coach'),
      table(['Former player rating', 'Future coaching identity'], [
        ['3-star', 'Developer of overlooked talent'],
        ['4-star', 'Evaluator of late bloomers who balances talent with patience'],
        ['5-star', 'Quarterback manager who understands elite expectations and crowded rooms'],
      ]),
    ],
  },
  {
    id: 'quick-reference',
    number: 14,
    title: 'Quick Reference Checklists',
    stage: 'Ongoing reference',
    content: [
      subheading('Before committing'),
      bullets([
        'Check the in-game QB ages, overalls and eligibility.',
        'Confirm the offensive playbook fits a dual-threat quarterback.',
        'Score the school using the commitment scorecard.',
        'Identify the likely year the starting job opens.',
        'Choose between loyalty, development and opportunity.',
        'Do not let prestige outweigh a blocked depth chart.',
      ]),
      subheading('After every game'),
      table(['Track', 'Notes'], [
        ['Final score', ''],
        ['Passing line', ''],
        ['Rushing line', ''],
        ['Turnovers', ''],
        ['Defining play', ''],
        ['Biggest mistake', ''],
        ['Health / wear', ''],
        ['Depth-chart storyline', ''],
      ]),
      subheading('End-of-season review'),
      bullets([
        'Did the role match the expected seasonal arc?',
        'Did your play style remain pass-first rather than scramble-first?',
        'Did your development reflect actual strengths and weaknesses?',
        'Did the coaching staff or scheme change?',
        'Is staying still the realistic choice?',
        'What single storyline should define next season?',
      ]),
    ],
  },
]);
