import { CAREER_SCHEMA_VERSION } from './weeklyEngine';

export const DEFAULT_CAREER_STATE = {
  schemaVersion: CAREER_SCHEMA_VERSION,
  careerPhase: 'Player',
  player: {
    name: '',
    pos: 'QB',
    number: '',
    school: '',
    height: '',
    weight: '',
    stars: '',
    overall: '',
    archetype: '',
    nationalQbRank: '',
    headshot: '',
    isCommitted: false,
    college: '',
  },
  coach: {
    prestige: '',
    security: '',
    contractRemaining: '',
    contractYear: '',
    budget: '',
    almaMaterStatus: '',
    dynastyPoints: '',
    recruitingNIL: '',
    rosterNIL: '',
    staffBudget: '',
    facilitiesBudget: '',
    rosterSize: '',
    scholarshipsUsed: '',
    portalDepartures: '',
    openScholarships: '',
    classCommits: '',
    portalAdditions: '',
  },
  currentSeason: 1,
  currentWeek: 1,
  playoffPicture: '',
  gameLogs: [],
  recruiting: [],
  rtg: {
    gpa: '',
    energy: '',
    coachTrust: '',
    trustToNext: '',
    rank: '',
    skillPoints: '',
    followers: '',
    valuation: '',
    sponsorships: '',
    wear: { arm: '', legs: '', chest: '', head: '' },
  },
  latestQuote: '',
  outletImages: {
    broadsheet: '',
    on3: '',
    local: '',
    filmroom: '',
    podcast: '',
  },
  trophies: [],
  rumors: [],
  podcastAudio: '',
  hasCloudAudio: false,
  weeklyUpdates: [],
  factLedger: [],
  careerMilestones: [],
  careerChronicle: [],
  newsroomIssues: [],
  newsroomMediaLibrary: [],
  newsroomMediaSettings: {
    autoGenerateLead: false,
  },
  retentionBoard: [],
  podcastEpisodes: [],
};
