import { CAREER_SCHEMA_VERSION } from './weeklyEngine.js';
import { DEFAULT_PLAYER_RECRUITING } from './playerRecruiting.js';
import { DEFAULT_CAREER_TRANSITIONS } from './careerTransitions.js';
import { DEFAULT_COLLEGE_NEWSROOM } from './collegeNewsroom.js';
import { DEFAULT_PLAYER_VISUAL_PROFILE } from './playerVisualProfile.js';

export const DEFAULT_CAREER_STATE = {
  schemaVersion: CAREER_SCHEMA_VERSION,
  careerPhase: 'Player',
  player: {
    name: '',
    pos: 'QB',
    number: '',
    school: '',
    height: '',
    weight: '',
    stars: '',
    overall: '',
    archetype: '',
    nationalQbRank: '',
    headshot: '',
    visualProfile: DEFAULT_PLAYER_VISUAL_PROFILE,
    isCommitted: false,
    college: '',
  },
  coach: {
    prestige: '',
    security: '',
    contractRemaining: '',
    contractYear: '',
    budget: '',
    almaMaterStatus: '',
    dynastyPoints: '',
    recruitingNIL: '',
    rosterNIL: '',
    staffBudget: '',
    facilitiesBudget: '',
    rosterSize: '',
    scholarshipsUsed: '',
    portalDepartures: '',
    openScholarships: '',
    classCommits: '',
    portalAdditions: '',
  },
  currentSeason: 1,
  currentWeek: 1,
  playoffPicture: '',
  gameLogs: [],
  recruiting: [],
  playerRecruiting: DEFAULT_PLAYER_RECRUITING,
  careerTransitions: DEFAULT_CAREER_TRANSITIONS,
  collegeNewsroom: DEFAULT_COLLEGE_NEWSROOM,
  rtg: {
    gpa: '',
    energy: '',
    coachTrust: '',
    trustToNext: '',
    rank: '',
    skillPoints: '',
    followers: '',
    valuation: '',
    sponsorships: '',
    weeklyPoints: '',
    coachHappiness: '',
    draftProjection: '',
    academicsStanding: '',
    examWeeks: '',
    academicsAbility: '',
    academicsCoachHappinessBonus: '',
    leadershipLevel: '',
    leadershipAbility: '',
    leadershipCoachHappinessBonus: '',
    leadershipTeamXpMultiplier: '',
    leadershipComposureBonus: '',
    healthLevel: '',
    injuryRisk: '',
    healthWearImpact: '',
    fitnessLevel: '',
    fitnessCoachHappinessBonus: '',
    fitnessTeamXpMultiplier: '',
    fitnessComposureBonus: '',
    fitnessWeightBonus: '',
    fitnessWearImpact: '',
    brandTier: '',
    nextFanMilestone: '',
    brandEngagement: '',
    dealTier: '',
    brandAbility: '',
    nilWeeklyCost: '',
    openNilSlots: '',
    wear: { arm: '', legs: '', chest: '', head: '' },
  },
  latestQuote: '',
  outletImages: {
    broadsheet: '',
    on3: '',
    local: '',
    filmroom: '',
    podcast: '',
  },
  podcastBranding: {
    version: 2,
    coverUrl: '',
  },
  trophies: [],
  rumors: [],
  podcastAudio: '',
  hasCloudAudio: false,
  weeklyAgendaDraft: null,
  weeklyUpdates: [],
  factLedger: [],
  careerMilestones: [],
  careerChronicle: [],
  newsroomIssues: [],
  postgameFrontPages: [],
  newsroomMediaLibrary: [],
  newsroomMediaSettings: {
    autoAssignLibrary: true,
    smartRecommendations: true,
    requirePhotoQaApproval: true,
    conferenceOverrides: {},
  },
  retentionBoard: [],
  podcastEpisodes: [],
};
