const clean = (value) => String(value ?? '').trim().toLowerCase();

const genericByeHeadline = (headline = '') => (
  /development work on the record/i.test(String(headline || ''))
  || /becomes part of .* verified season timeline/i.test(String(headline || ''))
  || /^where .+ fits: .+ entering .+bye/i.test(String(headline || ''))
);

export const isRoutineByeScaffoldIssue = (issue = {}) => {
  const isBye = clean(issue.weekType) === 'bye' || clean(issue.editionType) === 'bye';
  if (!isBye || clean(issue.weekPhase) === 'preseason') return false;

  const headlines = (Array.isArray(issue.articles) ? issue.articles : [])
    .map((article) => String(article?.headline || '').trim())
    .filter(Boolean);
  const looksLikeScaffold = headlines.some(genericByeHeadline);
  const generated = clean(issue.editorialStatus) === 'generated';

  // Legacy regular-season byes were published as deterministic placeholder stories.
  // Keep a genuinely generated bye story if it cleared the editorial engine, but hide
  // routine scaffold copy from the Newsroom desks/archive.
  return looksLikeScaffold || !generated;
};

export const newsroomIssueIsVisible = (issue = {}) => !isRoutineByeScaffoldIssue(issue);
