import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, CloudUpload, FileImage, Headphones, Home, Menu, Newspaper, Play, RotateCcw, Search, ShieldCheck, Target, Trophy, X, Pause, CircleCheck, Settings2, Activity, Download } from 'lucide-react';
import BroadcastDashboard from '../components/BroadcastDashboard.jsx';
import stadium from '../assets/dynastyhq-football-stadium-bg.webp';
import helmets from '../assets/matchup-helmets.webp';
import podcastCover from '../assets/gridiron-grind-cover.webp';
import { loadDemo, publishDemo, sampleGame, seedDemo, STORAGE_KEY } from './store.js';
import './redesign.css';

const routes = [['home','Home',Home],['gameHub','Game Hub',Trophy],['import','Session Import',CloudUpload],['newsroom','Newsroom',Newspaper],['podcast','Podcast',Headphones],['chronicle','Career Chronicle',BookOpen],['ledger','Fact Ledger',ShieldCheck],['rtg','RTG Status',Activity],['career','My Career',Target]];
const aliases = {dashboard:'home',importSession:'import',dataEntry:'import',factLedger:'ledger'};
const readRoute=()=>{const [p='home',id='']=location.hash.replace('#','').split('/');return {page:routes.some(r=>r[0]===p)?p:'home',id};};
const Badge=({children,tone=''})=><span className={`badge ${tone}`}>{children}</span>;
const Btn=({children,onClick,primary=false,...props})=><button className={`btn ${primary?'primary':''}`} onClick={onClick} {...props}>{children}</button>;
const Stats=({items})=><div className="stat-grid">{items.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>;
const Panel=({title,children,action,className=''})=><section className={`panel ${className}`}><div className="panel-top"><h2>{title}</h2>{action}</div>{children}</section>;
const Title=({eyebrow,title,description,action})=><header className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</header>;

export default function App(){
 const [state,setState]=useState(loadDemo),[route,setRoute]=useState(readRoute),[menu,setMenu]=useState(false),[notice,setNotice]=useState(''),[resetOpen,setResetOpen]=useState(false);
 const main=useRef(null);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch{setNotice('Browser storage is unavailable. Changes will last for this visit only.');}},[state]);
 useEffect(()=>{const onHash=()=>{setRoute(readRoute());setMenu(false);window.scrollTo(0,0);};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[]);
 useEffect(()=>{document.title=`${routes.find(r=>r[0]===route.page)?.[1]} · DynastyHQ Preview`;main.current?.focus({preventScroll:true});},[route.page,route.id]);
 useEffect(()=>{const escape=e=>{if(e.key==='Escape'){setMenu(false);setResetOpen(false);}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
 const go=(page,id='')=>{const p=aliases[page]||page;location.hash=`${p}${id?'/'+id:''}`;setMenu(false);};
 const publish=(draft,options)=>{const next=publishDemo(state,draft,options);setState(next);setNotice(`Week ${draft.week} confirmed. Your game, facts, Chronicle and coverage are updated.`);};
 const {page,id}=route;
 return <div className="demo-app" style={{'--stadium':`url(${stadium})`}}>
  <a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();main.current?.focus();}}>Skip to content</a>
  <header className="site-header"><div className="topline"><button className="wordmark" onClick={()=>go('home')} aria-label="DynastyHQ home">DYNASTY<b>HQ</b><small>YOUR CAREER. YOUR LEGACY.</small></button><div className="desktop-context"><span className="live-dot"/>COLLEGE FOOTBALL 27 <i/> SEASON 1 · WEEK {state.currentWeek}</div><div className="top-actions"><Badge tone="preview">DEMO PREVIEW</Badge><button className="icon-button" onClick={()=>setResetOpen(true)} aria-label="Reset demo"><RotateCcw size={17}/></button><button className="avatar" onClick={()=>go('career')} aria-label="Open player profile">JH</button><button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="main-nav">{menu?<X/>:<Menu/>}</button></div></div>
  <nav id="main-nav" className={`main-nav ${menu?'is-open':''}`} aria-label="Main navigation">{routes.map(([key,label,Icon])=><a key={key} href={`#${key}`} aria-current={page===key?'page':undefined}><Icon size={15}/>{label}</a>)}</nav>
  <div className="scorebar"><b><span className="live-dot"/> CAREER FEED</b><span>CINCINNATI <strong>{state.gameLogs.filter(g=>g.result==='W').length}–{state.gameLogs.filter(g=>g.result==='L').length}</strong></span>{state.gameLogs.slice(-2).map(g=><button key={g.week} onClick={()=>go('gameHub',g.week)}>WK {g.week}<strong>CIN {g.homeScore}</strong><span>{g.opponent} {g.awayScore}</span><em>FINAL</em></button>)}<span className="sample-caption">ILLUSTRATIVE CAREER DATA</span></div></header>
  {notice&&<div className="notice" role="status"><CircleCheck size={17}/>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification"><X size={16}/></button></div>}
  <main id="main-content" ref={main} tabIndex={-1} className={page==='home'?'home-content':'workspace'}>
  {page==='home'?<><div className="home-intro"><span className="eyebrow">THE COLLEGE YEARS</span><span>Jordan Hayes · Cincinnati · Freshman</span></div><BroadcastDashboard state={state} onNavigate={go}/></>:null}
  {page==='import'&&<ImportPage state={state} onPublish={publish} go={go}/>}
  {page==='gameHub'&&<GameHub state={state} selected={id} go={go}/>}
  {page==='newsroom'&&<Newsroom state={state} selected={id} go={go}/>}
  {page==='podcast'&&<Podcast state={state} go={go}/>}
  {page==='chronicle'&&<Chronicle state={state} go={go}/>}
  {page==='ledger'&&<Ledger state={state} go={go}/>}
  {page==='rtg'&&<Rtg state={state} onSave={rtg=>{setState(s=>({...s,rtg:{...s.rtg,...rtg}}));setNotice('Demo RTG status saved. Historical week snapshots are unchanged.');}} go={go}/>}
  {page==='career'&&<Career state={state} go={go}/>}
  </main>
  <footer className="site-footer"><span>DYNASTY<b>HQ</b> <i/> BUILT FOR THE SATURDAYS THAT STAY WITH YOU.</span><span>Isolated demo · Saved in this browser</span></footer>
  <nav className="bottom-nav" aria-label="Mobile quick navigation">{routes.slice(0,5).filter(r=>r[0]!=='podcast').map(([key,label,Icon])=><a href={`#${key}`} key={key} aria-current={page===key?'page':undefined}><Icon size={19}/><span>{key==='import'?'Import':label}</span></a>)}<button onClick={()=>{setMenu(true);window.scrollTo(0,0);}}><Menu size={19}/><span>More</span></button></nav>
  {resetOpen&&<div className="modal-backdrop"><section className="panel reset-modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><h2 id="reset-title">Start the demo over?</h2><p>This removes this browser’s demo imports and edits, then restores the sample career.</p><div className="button-row"><Btn autoFocus onClick={()=>setResetOpen(false)}>Keep exploring</Btn><Btn primary onClick={()=>{setState(seedDemo());setResetOpen(false);go('home');setNotice('Sample career restored.');}}>Reset sample career</Btn></div></section></div>}
 </div>;
}

function ImportPage({state,onPublish,go}){
 const [phase,setPhase]=useState(0),[files,setFiles]=useState([]),[draft,setDraft]=useState(()=>sampleGame(state.currentWeek)),[sample,setSample]=useState(true),[error,setError]=useState(''),[verified,setVerified]=useState(false),[finishedWeek,setFinishedWeek]=useState(null);
 const input=useRef(); const urls=useRef([]);
 useEffect(()=>()=>urls.current.forEach(URL.revokeObjectURL),[]);
 const addFiles=list=>{setError('');const incoming=Array.from(list);if(incoming.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type))){setError('Use JPG, PNG, or WebP screenshots.');return;}if(files.length+incoming.length>30||incoming.some(f=>f.size>10*1024*1024)){setError('Choose up to 30 screenshots, each under 10 MB.');return;}setFiles(old=>[...old,...incoming.map(f=>{const url=URL.createObjectURL(f);urls.current.push(url);return {name:f.name,url};})]);setSample(false);setDraft(d=>({...d,homeScore:'',awayScore:'',passYds:'',passTD:'',rushYds:'',rushTD:'',int:''}));};
 const loadSample=()=>{setFiles([{name:'Week '+state.currentWeek+' · Final score',kind:'Scoreboard'},{name:'Jordan Hayes · Player stats',kind:'Box score'},{name:'Player hub · RTG status',kind:'Player hub'}]);setSample(true);setDraft(sampleGame(state.currentWeek));setError('');};
 const confirm=()=>{try{onPublish(draft,{sample,sources:files.map(f=>({name:f.name,fileName:f.name}))});setFinishedWeek(draft.week);setPhase(2);}catch(e){setError(e.message);}};
 return <><Title eyebrow={`SEASON 1 / WEEK ${finishedWeek||state.currentWeek}`} title="Every screenshot. One story." description="Bring your session together. Review the facts once, then follow the week across your career."/>
 <div className="step-rail">{['Add screenshots','Review & confirm','Week connected'].map((label,i)=><div className={phase>=i?'active':''} key={label}><span>{phase>i?<Check size={14}/>:i+1}</span>{label}</div>)}</div>
 {phase===0&&<div className="two-col"><Panel title="Session Import"><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files);}}><CloudUpload size={40}/><h2>Your Saturday starts here.</h2><p>Drop screenshots here, or choose them from your device.</p><Btn primary onClick={()=>input.current.click()}>Choose screenshots <ArrowRight size={16}/></Btn><input ref={input} type="file" multiple accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{addFiles(e.target.files);e.target.value='';}}/><small>JPG, PNG, WebP · Up to 30 files · 10 MB each</small></div><div className="sample-load"><div><strong>Take the complete flow for a spin.</strong><p>Load a prepared sample session with editable facts.</p></div><Btn onClick={loadSample}>Load sample session</Btn></div>{files.length>0&&<><div className="file-grid">{files.map((f,i)=><div className="file-tile" key={f.name+i}>{f.url?<img src={f.url} alt={f.name}/>:<div className="sample-image"><FileImage/><b>{f.kind}</b><small>SAMPLE SCREEN</small></div>}<span>{f.name}</span><button aria-label={`Remove ${f.name}`} onClick={()=>setFiles(fs=>fs.filter((_,j)=>j!==i))}><X size={14}/></button></div>)}</div><div className="button-row end"><span>{files.length} screenshots ready</span><Btn primary onClick={()=>{setError('');setPhase(1);}}>Review {sample?'sample facts':'manual entries'} <ArrowRight size={16}/></Btn></div></>}</Panel><aside><Panel title="What belongs in a session?"><ul className="check-list"><li><Check/>Final score and player statistics</li><li><Check/>Player hub and depth-chart status</li><li><Check/>EA SPORTS Network coverage</li><li><Check/>Progression and career moments</li></ul></Panel><div className="callout"><ShieldCheck/><div><strong>You control the record.</strong><p>The demo uses prepared sample facts. Your own screenshots can be previewed and entered manually; live AI scanning is not connected here.</p></div></div></aside></div>}
 {phase===1&&<div className="two-col"><Panel title={sample?'Review sample facts':'Enter facts from your screenshots'} action={<Badge>WEEK {draft.week}</Badge>}><p className="muted">{sample?'Prepared sample values. Edit anything before confirming.':'Read your screenshots and enter the values below. No automated extraction has been run.'}</p><div className="form-grid"><label className="full">Opponent<input value={draft.opponent} onChange={e=>{setDraft({...draft,opponent:e.target.value});setVerified(false);}}/></label>{[['homeScore','Cincinnati score'],['awayScore','Opponent score'],['passYds','Passing yards'],['passTD','Passing TD'],['rushYds','Rushing yards'],['rushTD','Rushing TD'],['int','Interceptions']].map(([key,label])=><label key={key}>{label}<input type="number" min={key==='rushYds'?undefined:0} step="1" value={draft[key]} onChange={e=>{setDraft({...draft,[key]:e.target.value});setVerified(false);}}/></label>)}</div><label className="confirm-check"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I reviewed these values and want them in the demo career.</label><div className="button-row"><Btn onClick={()=>{setPhase(0);setError('');}}><ArrowLeft size={15}/> Back</Btn><Btn primary disabled={!verified} onClick={confirm}>Confirm & publish demo week <Check size={16}/></Btn></div></Panel><aside><Panel title="Session evidence"><div className="evidence-list">{files.map((f,i)=><div key={i}>{f.url?<img src={f.url} alt={f.name}/>:<FileImage/>}<span>{f.name}</span></div>)}</div></Panel><Panel title="This confirmation updates"><ul className="check-list">{['Game result and player statistics','Fact Ledger and Career Chronicle','Local recap and podcast script','Current week on the homepage'].map(t=><li key={t}><Check/>{t}</li>)}</ul><p className="muted">Publishes only to this browser’s sample career.</p></Panel></aside></div>}
 {phase===2&&<Panel className="success-card" title="Your week is connected."><div className="success-icon"><CircleCheck size={38}/></div><h2>Week {finishedWeek} is in the books.</h2><p>One confirmation. A permanent game page, linked facts, a Chronicle entry, and fresh sample coverage.</p><div className="button-row center"><Btn primary onClick={()=>go('gameHub',finishedWeek)}>Explore the Game Hub <ArrowRight size={16}/></Btn><Btn onClick={()=>go('newsroom')}>Read the recap</Btn></div></Panel>}
 {error&&<p className="error" role="alert">{error}</p>}
 </>;
}

function GameHub({state,selected,go}){
 const games=[...state.gameLogs].reverse(); const game=selected?games.find(g=>String(g.week)===selected):null; const current=!game;
 const week=game?.week||state.currentWeek; const opponent=game?.opponent||state.currentWeekSetup.opponent; const publication=`season-1-week-${week}`;const article=state.newsroomIssues.flatMap(i=>i.articles).find(a=>a.publicationId===publication);const [tab,setTab]=useState('Overview');
 useEffect(()=>setTab('Overview'),[selected]);
 return <><Title eyebrow="YOUR SATURDAY / ALL IN ONE PLACE" title="Game Hub" description="The result, the evidence, and everything this game means for your career." action={<label className="select-label">Game<select value={game?String(game.week):'current'} onChange={e=>go('gameHub',e.target.value==='current'?'':e.target.value)}><option value="current">Week {state.currentWeek} · Upcoming</option>{games.map(g=><option key={g.week} value={g.week}>Week {g.week} · {g.opponent}</option>)}</select></label>}/>
 <section className="matchup-card"><div className="eyebrow">SEASON 1 · WEEK {week} <Badge tone={game?'green':''}>{game?'FINAL':'UP NEXT'}</Badge></div><div className="matchup"><div><small>BEARCATS</small><h2>CINCINNATI</h2><span>{game?'HOME':'NIPPERT STADIUM'}</span></div><div className="matchup-center"><img src={helmets} alt="Two football helmets"/><strong>{game?`${game.homeScore} – ${game.awayScore}`:'VS'}</strong></div><div><small>THE MATCHUP</small><h2>{opponent.toUpperCase()}</h2><span>{game?'VISITOR':'SATURDAY · 7:30 PM'}</span></div></div><div className="matchup-footer"><span><span className="live-dot"/>{game?'Confirmed in demo career':'Ready for your next session'}</span><Btn primary onClick={()=>go(current?'import':'ledger')}>{current?'Import session':'View verified facts'} <ChevronRight size={16}/></Btn></div></section>
 <div className="tabs" role="tablist" aria-label="Game details">{['Overview','Player stats','Coverage','Photos'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {current?<div className="two-col"><Panel title="The week ahead"><h3>Play the game. Bring back the story.</h3><p>Capture the result, player stats, and RTG status. Session Import brings the whole week into one review.</p><Btn onClick={()=>go('import')}>Open Session Import <ArrowRight size={15}/></Btn></Panel><Panel title="Pregame player snapshot"><Stats items={[["DEPTH CHART",state.rtg.rank],["OVERALL",state.player.overall],["ENERGY",state.rtg.energy],["COACH TRUST",state.rtg.coachTrust]]}/><Btn onClick={()=>go('rtg')}>View RTG status</Btn></Panel></div>:<>
 {tab==='Overview'&&<div className="two-col"><Panel title="From the box score"><Stats items={[["PASS YDS",game.passYds],["PASS TD",game.passTD],["RUSH YDS",game.rushYds],["INT",game.int]]}/><p>Jordan Hayes · {state.weeklyUpdates.find(w=>w.week===week)?.rtgSnapshot?.rank||'QB2'} at the time of this game.</p><Btn onClick={()=>setTab('Player stats')}>Full player statistics</Btn></Panel><Panel title="Career impact"><ul className="check-list"><li><Check/>Result added to season record</li><li><Check/>Week {week} saved in the Career Chronicle</li><li><Check/>Game facts linked to source evidence</li></ul><Btn onClick={()=>go('chronicle')}>Follow the career story</Btn></Panel></div>}
 {tab==='Player stats'&&<Panel title="Jordan Hayes · Game statistics"><Stats items={[["PASSING YARDS",game.passYds],["PASSING TD",game.passTD],["RUSHING YARDS",game.rushYds],["RUSHING TD",game.rushTD],["INTERCEPTIONS",game.int]]}/><p className="muted">Confirmed values for this game. Player status uses the saved weekly snapshot.</p></Panel>}
 {tab==='Coverage'&&<div className="two-col"><Panel title="The local story"><Badge>SAMPLE RECAP</Badge><h3>{article?.headline||'Recap pending'}</h3><Btn onClick={()=>go('newsroom',article?.id)}>Read the article <ArrowRight size={15}/></Btn></Panel><Panel title="In your headphones"><h3>Week {week}: {opponent} in review</h3><p>The podcast script follows the same confirmed facts.</p><Btn onClick={()=>go('podcast')}>Open podcast studio <Headphones size={16}/></Btn></Panel></div>}
 {tab==='Photos'&&<Panel title="Session evidence"><div className="evidence-list">{(state.demoSources?.[publication]||[]).map((s,i)=><div key={i}><FileImage/><span>{s.name}</span><Badge>REFERENCE</Badge></div>)}</div><p className="muted">Uploaded screenshot previews are temporary. This demo retains their filenames; it does not upload your media.</p><img className="photo-strip" src={stadium} alt="Illustrative football stadium at night"/><small>Illustrative stadium artwork · Not a captured game photo</small></Panel>}
 </>}
 </>;
}

function Newsroom({state,selected,go}){
 const [filter,setFilter]=useState('All coverage'),[query,setQuery]=useState('');const articles=state.newsroomIssues.flatMap(i=>i.articles).reverse();const active=articles.find(a=>a.id===selected);
 if(active)return <><Btn onClick={()=>go('newsroom')}><ArrowLeft size={16}/> Back to Newsroom</Btn><article className="reader"><div className="reader-photo" style={{backgroundImage:`linear-gradient(0deg,#07131f,transparent),url(${stadium})`}}/><div className="reader-content"><Badge>LOCAL / SAMPLE RECAP</Badge><h1>{active.headline}</h1><p className="article-meta">DYNASTYHQ DESK · SEASON 1 · WEEK {active.week}</p>{active.body.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}<div className="reader-evidence"><ShieldCheck/><div><strong>One story. A traceable record.</strong><p>Based on the confirmed Week {active.week} game and player snapshot.</p><div className="button-row"><Btn onClick={()=>go('gameHub',active.week)}>Open game</Btn><Btn onClick={()=>go('ledger')}>View Fact Ledger</Btn></div></div></div></div></article></>;
 const filtered=articles.filter(a=>(filter==='All coverage'||filter==='Local')&&`${a.headline} ${a.body}`.toLowerCase().includes(query.toLowerCase()));
 return <><Title eyebrow="THE STORIES BEHIND THE SATURDAYS" title="Newsroom" description="Your career, covered. Every edition starts with the facts you confirmed."/><div className="toolbar"><div className="tabs">{['All coverage','Local','National','EA SPORTS Network'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><label className="search"><Search size={16}/><input aria-label="Search coverage" placeholder="Search the coverage" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {filtered.length?<><button className="lead-story" onClick={()=>go('newsroom',filtered[0].id)}><img src={stadium} alt="Stadium under the lights"/><div><Badge>LOCAL · WEEK {filtered[0].week}</Badge><h2>{filtered[0].headline}</h2><p>A result on the field. Another chapter in the making.</p><span>READ THE STORY <ArrowRight size={17}/></span></div></button><div className="story-grid">{filtered.slice(1).map(a=><button className="story-card" key={a.id} onClick={()=>go('newsroom',a.id)}><div className="story-thumb" style={{backgroundImage:`url(${stadium})`}}><span>WEEK {a.week}</span></div><div><Badge>SAMPLE LOCAL COVERAGE</Badge><h3>{a.headline}</h3><span>Read article <ArrowRight size={15}/></span></div></button>)}</div></>:<Panel title={query?'No matching coverage':`${filter} coverage`}><p>{query?'Try another search or clear the filter.':filter==='EA SPORTS Network'?'Your imported in-game articles will live here, distinct from DynastyHQ-generated coverage. This sample career has no imported EA SPORTS Network articles.':'No national coverage is attached to this sample career yet.'}</p><Btn onClick={()=>{setQuery('');setFilter('All coverage');}}>View available stories</Btn></Panel>}
 </>;
}

function Podcast({state,go}){
 const episodes=[...state.podcastEpisodes].reverse();const [selected,setSelected]=useState(episodes[0]?.id),[playing,setPlaying]=useState(false),[audioError,setAudioError]=useState('');const episode=episodes.find(e=>e.id===selected)||episodes[0];
 useEffect(()=>()=>{window.speechSynthesis?.cancel();},[]);
 const speak=()=>{if(playing){window.speechSynthesis?.cancel();setPlaying(false);return;}if(!window.speechSynthesis){setAudioError('Browser narration is unavailable. The complete episode script is below.');return;}const u=new SpeechSynthesisUtterance(episode.script.replace(/This is an illustrative[\s\S]*/,''));u.rate=.95;u.onend=()=>setPlaying(false);u.onerror=()=>{setPlaying(false);setAudioError('Narration could not play in this browser. You can read the script below.');};window.speechSynthesis.cancel();window.speechSynthesis.speak(u);setPlaying(true);};
 return <><Title eyebrow="THE SOUND OF YOUR SEASON" title="Podcast" description="The same career. A different way to relive it."/><div className="podcast-feature panel"><div className="podcast-art"><img src={podcastCover} alt="Football podcast cover artwork"/><span>DYNASTYHQ ORIGINAL</span></div><div className="podcast-detail"><Badge>SAMPLE EPISODE / WEEK {episode.week}</Badge><h1>THE HUDDLE</h1><h2>{episode.title}</h2><p>A concise postgame review grounded in your confirmed game and player status.</p><div className="waveform" aria-hidden="true">{Array.from({length:45},(_,i)=><i key={i} style={{height:10+(i*17%42)+'px'}}/>)}</div><div className="button-row"><Btn primary onClick={speak}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?'Stop narration':'Play browser narration'}</Btn><Btn onClick={()=>go('gameHub',episode.week)}>View game</Btn></div><small>Browser voice preview · A produced podcast audio track is not attached.</small>{audioError&&<p role="status">{audioError}</p>}</div></div><div className="two-col"><Panel title="Episode script"><div className="script">{episode.script.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}</div></Panel><Panel title="From the archive">{episodes.map(e=><button className={`list-row ${episode.id===e.id?'selected':''}`} key={e.id} onClick={()=>{window.speechSynthesis?.cancel();setPlaying(false);setSelected(e.id);}}><Headphones/><span><strong>{e.title}</strong><small>Week {e.week} · Script ready</small></span><ChevronRight size={16}/></button>)}</Panel></div></>;
}

function Chronicle({state,go}){
 const [query,setQuery]=useState('');const entries=[...state.careerChronicle].reverse().filter(e=>`${e.title} ${e.summary}`.toLowerCase().includes(query.toLowerCase()));
 return <><Title eyebrow="MOMENTS BECOME MILESTONES" title="Career Chronicle" description="A living record of the climb. The games, the growth, and the moments worth keeping."/><div className="two-col chronicle-layout"><Panel title="Chapter 01 · The college years"><div className="chapter-banner"><span>01</span><div><Badge>CINCINNATI / FRESHMAN</Badge><h2>Every rep writes the next page.</h2><p>A developing quarterback finding his place.</p></div></div><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a career moment" aria-label="Search Chronicle"/></label><div className="timeline">{entries.map((e,i)=><button key={e.id} onClick={()=>go('gameHub',e.week)}><div className="timeline-dot">{i===0?<Trophy size={15}/>:<Check size={14}/>}</div><span className="eyebrow">SEASON {e.season} · WEEK {e.week}</span><h3>{e.title}</h3><p>{e.summary}</p><small>Explore game <ArrowRight size={13}/></small></button>)}{!entries.length&&<p>No matching moments. Try a different search.</p>}</div></Panel><aside><Panel title="Career at a glance"><Stats items={[["OVERALL",state.player.overall],["DEPTH CHART",state.rtg.rank],["GAMES LOGGED",state.gameLogs.length],["CHAPTER",'01']]}/><Btn onClick={()=>go('career')}>View player profile</Btn></Panel><Panel title="The record behind the story"><p>Each published week connects to verified facts and its saved player snapshot. Later rating changes don’t rewrite earlier moments.</p><Btn onClick={()=>go('ledger')}><ShieldCheck size={16}/> Open Fact Ledger</Btn></Panel></aside></div></>;
}
function Ledger({state,go}){
 const [query,setQuery]=useState(''),[week,setWeek]=useState('all');const facts=state.factLedger.filter(f=>(week==='all'||f.publicationId===`season-1-week-${week}`)&&`${f.label} ${f.key} ${f.value}`.toLowerCase().includes(query.toLowerCase())).slice().reverse();
 const exportFacts=()=>{const blob=new Blob([JSON.stringify(facts,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='dynastyhq-demo-facts.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <><Title eyebrow="THE SOURCE OF YOUR STORY" title="Fact Ledger" description="A clear record of what happened, when it happened, and which week it belongs to." action={<Btn onClick={exportFacts}><Download size={15}/> Export filtered facts</Btn>}/><Panel title={`${facts.length} confirmed demo facts`}><div className="toolbar"><label className="search"><Search size={16}/><input aria-label="Search facts" placeholder="Search player, score, trust…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="select-label">Week<select value={week} onChange={e=>setWeek(e.target.value)}><option value="all">All weeks</option>{state.gameLogs.map(g=><option key={g.week} value={g.week}>Week {g.week}</option>)}</select></label></div><div className="table-scroll"><table><thead><tr><th>FACT</th><th>VALUE</th><th>WEEK</th><th>STATUS</th><th>SOURCE</th></tr></thead><tbody>{facts.map((f,i)=>{const wk=f.publicationId?.split('-').at(-1);return <tr key={f.id||i}><td><strong>{f.label||f.key}</strong><small>{f.key}</small></td><td>{String(f.value)}</td><td><button className="text-button" onClick={()=>go('gameHub',wk)}>Week {wk}</button></td><td><Badge tone="green"><Check size={12}/> CONFIRMED</Badge></td><td>{state.demoSources?.[f.publicationId]?.[0]?.name||'Demo publication'}</td></tr>;})}</tbody></table>{!facts.length&&<p>No matching facts. Clear the search or choose another week.</p>}</div></Panel></>;
}
function Rtg({state,onSave,go}){
 const [editing,setEditing]=useState(false),[draft,setDraft]=useState(state.rtg);const history=state.weeklyUpdates.slice().reverse();
 return <><Title eyebrow="THE PLAYER BEHIND THE NUMBER" title="RTG Status" description="Your current role, weekly readiness, and the development that got you here." action={<Btn onClick={()=>{setDraft(state.rtg);setEditing(!editing);}}><Settings2 size={16}/>{editing?'Cancel editing':'Edit demo snapshot'}</Btn>}/><Panel title="Current player snapshot" action={<Badge>WEEK {state.currentWeek}</Badge>}><Stats items={[["OVERALL",state.player.overall],["DEPTH CHART",state.rtg.rank],["COACH TRUST",Number(state.rtg.coachTrust).toLocaleString()],["SKILL POINTS",state.rtg.skillPoints],["ENERGY",state.rtg.energy],["GPA",state.rtg.gpa]]}/>{editing&&<form onSubmit={e=>{e.preventDefault();onSave(draft);setEditing(false);}}><div className="form-grid">{[['coachTrust','Coach trust',0,100000],['skillPoints','Skill points',0,100000],['energy','Energy',0,100],['gpa','GPA',0,4]].map(([key,label,min,max])=><label key={key}>{label}<input required type="number" step={key==='gpa'?'.1':'1'} min={min} max={max} value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></label>)}<label>Depth-chart role<select value={draft.rank} onChange={e=>setDraft({...draft,rank:e.target.value})}>{['QB1','QB2','QB3'].map(x=><option key={x}>{x}</option>)}</select></label></div><Btn primary type="submit">Save demo snapshot</Btn></form>}</Panel><div className="two-col"><Panel title="Development outlook"><Badge tone="green">RESTRAINED PROGRESSION</Badge><h3>Build the player. Keep the climb.</h3><p>A freshman QB2 with limited snaps has room to develop without spending the whole bank. Use the current ratings and last upgrade to decide when the next small step is due.</p><p className="muted">This sample career has no confirmed last-upgrade date or purchase costs. No specific upgrade has been authorized.</p><Btn onClick={()=>go('import')}>Bring in a new status snapshot</Btn></Panel><Panel title="Saved weekly snapshots">{history.map(w=><button className="list-row" key={w.id} onClick={()=>go('gameHub',w.week)}><Activity/><span><strong>Week {w.week} · {w.rtgSnapshot.rank}</strong><small>Trust {w.rtgSnapshot.coachTrust} · Energy {w.rtgSnapshot.energy} · GPA {w.rtgSnapshot.gpa}</small></span><ChevronRight size={16}/></button>)}</Panel></div></>;
}
function Career({state,go}){return <><Title eyebrow="ONE CAREER. YOUR ENTIRE JOURNEY." title="My Career" description="From the first opportunity to the legacy you leave behind."/><section className="profile-hero panel"><div className="jersey">12</div><div><Badge>ILLUSTRATIVE DEMO PLAYER</Badge><h1>JORDAN HAYES</h1><p>Cincinnati · Quarterback · Freshman</p><span className="profile-meta">6′ 2″ &nbsp; / &nbsp; 205 LB &nbsp; / &nbsp; DUAL THREAT &nbsp; / &nbsp; 3-STAR RECRUIT</span></div><div className="ovr"><strong>{state.player.overall}</strong><span>OVERALL</span></div></section><div className="two-col"><Panel title="The college years"><Stats items={[["DEPTH CHART",state.rtg.rank],["CURRENT WEEK",state.currentWeek],["GAMES LOGGED",state.gameLogs.length],["BANKED POINTS",state.rtg.skillPoints]]}/><div className="button-row"><Btn primary onClick={()=>go('rtg')}>View RTG status</Btn><Btn onClick={()=>go('chronicle')}>Open Career Chronicle</Btn></div></Panel><Panel title="Your career library">{[['gameHub','Game history','Results, statistics, and the story of each Saturday'],['newsroom','Media coverage','Your local career coverage and imported articles'],['podcast','Podcast archive','A season of stories, ready to revisit'],['ledger','Verified record','Facts connected to the week they happened']].map(([r,t,d])=><button className="list-row" key={r} onClick={()=>go(r)}><BookOpen/><span><strong>{t}</strong><small>{d}</small></span><ChevronRight size={16}/></button>)}</Panel></div></>;}

